global:
  scrape_interval: 50s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 60s # time between each evaluation of Prometheus' alerting rules

scrape_configs:
  - job_name: django
    static_configs:
      - targets:
        - django:8000
    scrape_interval: 60s
    scrape_timeout: 50s