name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        make -C src/scrapper docker/build
    - name: Lint
      run: |
        make -C src/scrapper docker/format/check
    - name: Unit tests
      run: |
        make -C src/scrapper docker/tests